name: Playwright Tests

on:
  push:
    branches: 
      - main
      - master
      - 'feature/**'
  pull_request:
    branches: 
      - main
      - master
      - 'feature/**'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node- 
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Determine changed test directories
      id: find-changed-tests
      run: |
        echo "FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^tests/' | awk -F '/' '{print $2}' | uniq)" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests conditionally
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          for dir in $FILES_CHANGED
          do
            if [ -d ${{ github.workspace }}/tests/$dir ]; then
              echo "Running tests in changed directory: $dir"
              npx playwright test ${{ github.workspace }}/tests/$dir --reporter=dot --reporter=html
            fi
          done
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "Running all tests because this is a pull request"
          npx playwright test ${{ github.workspace }}/tests/ --reporter=dot --reporter=html
        fi

    - name: Upload Playwright reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
